### ISSUE TITLE
Source and self shows [object object]

### ISSUE THREAD

**Issue by wiesson** [developit/nextjs-preact-demo#7]
I don't know if it's a bug, but I wanted to mention it, maybe someone can enlighten me. When running the development version, I see a lot of [object object]s in the dom tree.

<img width="916" alt="Screenshot 2020-04-03 at 22 26 37" src="https://user-images.githubusercontent.com/933231/78420255-b89bd080-764d-11ea-90af-91d02e9dadc2.png">

// edit: after a quick google search I found that issue https://github.com/preactjs/preact/issues/1058

> Okay create-react-app uses the babel plugins: transform-react-jsx-source and transform-react-jsx-self by default in none-production builds. Preact doesn't support those "special" attributes and just adds them as a stringified version to the dom.

I guess it's fine then :)

**Comment by developit** [comment]
Hiya - this was actually just an oversight and should be fixed on master.

The following two changes are what you'll want to copy into your project:

#### 1. automatically inject `preact/debug`

_This makes preact-devtools work and fixes the issue in your screenshot._

https://github.com/developit/nextjs-preact-demo/commit/c85f8a38d6bcd57367bf8ac7430debe4f3061cb6#diff-5d0c276360a637d1b787a57760665fbeR27-R35

#### 2. Add webpack aliases

_This fixes an issue where importing an npm dependency that uses React could end up bringing in a copy of the react package._

https://github.com/developit/nextjs-preact-demo/commit/f31d1dd6bbcf0d1392913274101a2af487e0b8c2#diff-5d0c276360a637d1b787a57760665fbeR26-R29


---

Closing since I'm fairly certain the above should have things working for you, but please re-open if that's not the case!

**Comment by yassinebridi** [comment]
@developit, I think this is still showing `__source="[object Object]"` in the latest master changes.

**Comment by mike-lischke** [comment]
It is indeed still showing __source and __self, still today, more than a year later :-(
